import type { Issue, Project } from '../types';
import { fetchIssues } from './issueService';
import { fetchProjects } from './projectService';
import { recordChange } from './auditService';

type ReportFormat = 'pdf' | 'html' | 'docx';

const esc = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');

const issuesTable = (issues: Issue[]) => {
  if (!issues.length) {
    return '<p>No findings available for this project.</p>';
  }

  const rows = issues
    .map(
      (issue) =>
        `<tr><td>${esc(issue.title || 'Untitled')}</td><td>${esc(issue.severity || 'Info')}</td><td>${esc(issue.state || 'Open')}</td><td>${esc(issue.cvssScore || '0')}</td><td>${esc(issue.updatedAt || '')}</td></tr>`
    )
    .join('');

  return `<table><thead><tr><th>Title</th><th>Severity</th><th>Status</th><th>CVSS</th><th>Updated</th></tr></thead><tbody>${rows}</tbody></table>`;
};

const htmlShell = (title: string, body: string) => `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(title)}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 2rem; color: #0f172a; }
    h1, h2, h3 { margin: 0 0 0.75rem; }
    h1 { font-size: 1.6rem; }
    p { color: #334155; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
    th, td { border: 1px solid #cbd5e1; text-align: left; padding: 0.5rem 0.6rem; font-size: 0.85rem; }
    th { background: #f8fafc; }
    .meta { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 0.5rem; margin: 1rem 0; }
    .meta div { padding: 0.75rem; border: 1px solid #e2e8f0; border-radius: 0.5rem; background: #f8fafc; }
    .caption { color: #64748b; font-size: 0.8rem; margin-top: 1rem; }
  </style>
</head>
<body>
${body}
</body>
</html>`;

const makeProjectHtml = (project: Project, issues: Issue[]) => {
  const total = issues.length;
  const critical = issues.filter((issue) => issue.severity === 'Critical').length;
  const high = issues.filter((issue) => issue.severity === 'High').length;
  const medium = issues.filter((issue) => issue.severity === 'Medium').length;
  const low = issues.filter((issue) => issue.severity === 'Low').length;

  return htmlShell(
    `Project Report - ${project.name}`,
    `<h1>${esc(project.name)} - Security Report</h1>
    <p>Client: ${esc(project.client)}</p>
    <div class="meta">
      <div><strong>Total Findings</strong><br/>${total}</div>
      <div><strong>Last Updated</strong><br/>${esc(project.lastUpdate || new Date().toISOString())}</div>
      <div><strong>Critical / High</strong><br/>${critical} / ${high}</div>
      <div><strong>Medium / Low</strong><br/>${medium} / ${low}</div>
    </div>
    <h2>Findings</h2>
    ${issuesTable(issues)}
    <p class="caption">Generated by Ducky Pwn Docs web app.</p>`
  );
};

const makeIssueHtml = (project: Project, issue: Issue) =>
  htmlShell(
    `Finding Report - ${issue.title || 'Untitled Finding'}`,
    `<h1>${esc(issue.title || 'Untitled Finding')}</h1>
    <p>Project: ${esc(project.name)} (${esc(project.client)})</p>
    <div class="meta">
      <div><strong>Severity</strong><br/>${esc(issue.severity || 'Info')}</div>
      <div><strong>Status</strong><br/>${esc(issue.state || 'Open')}</div>
      <div><strong>CVSS</strong><br/>${esc(issue.cvssScore || '0')}</div>
      <div><strong>Updated</strong><br/>${esc(issue.updatedAt || new Date().toISOString())}</div>
    </div>
    <h2>Description</h2>
    <p>${esc(issue.description || 'No description provided.')}</p>
    <h2>Solution</h2>
    <p>${esc(issue.solution || 'No remediation guidance provided.')}</p>
    <p class="caption">Generated by Ducky Pwn Docs web app.</p>`
  );

const downloadText = (filename: string, content: string, mimeType: string) => {
  if (typeof window === 'undefined') return;

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
};

const printHtml = (html: string) => {
  if (typeof window === 'undefined') return;
  const preview = window.open('', '_blank');
  if (!preview) {
    throw new Error('Popup blocked. Please allow popups to print PDF.');
  }
  preview.document.write(html);
  preview.document.close();
  preview.focus();
  preview.print();
};

export const generateReport = async (
  projectId: string,
  format: ReportFormat
): Promise<{ path: string } | { error: string } | null> => {
  const projects = await fetchProjects();
  const project = projects.find((entry) => entry.id === projectId);
  if (!project) return { error: 'Project not found.' };
  const issues = await fetchIssues(projectId);

  const html = makeProjectHtml(project, issues);

  if (format === 'html' || format === 'docx') {
    const ext = format === 'docx' ? 'html' : 'html';
    const filename = `${project.name.replaceAll(/\s+/g, '-').toLowerCase()}-report.${ext}`;
    downloadText(filename, html, 'text/html;charset=utf-8');
    recordChange({
      action: 'Generated project report',
      targetType: 'report',
      targetId: project.id,
      targetName: project.name,
      projectId: project.id,
      details: `Format: ${format}`,
    });
    return { path: filename };
  }

  if (format === 'pdf') {
    printHtml(html);
    recordChange({
      action: 'Generated project report',
      targetType: 'report',
      targetId: project.id,
      targetName: project.name,
      projectId: project.id,
      details: 'Format: pdf',
    });
    return { path: 'browser-print-dialog' };
  }

  return { error: 'Unsupported format.' };
};

export const generateIssueReport = async (
  projectId: string,
  issueId: string,
  format: ReportFormat
): Promise<{ path: string } | { error: string } | null> => {
  const projects = await fetchProjects();
  const project = projects.find((entry) => entry.id === projectId);
  if (!project) return { error: 'Project not found.' };

  const issues = await fetchIssues(projectId);
  const issue = issues.find((entry) => entry.id === issueId);
  if (!issue) return { error: 'Finding not found.' };

  const html = makeIssueHtml(project, issue);

  if (format === 'html' || format === 'docx') {
    const ext = format === 'docx' ? 'html' : 'html';
    const filename = `${(issue.title || 'finding').replaceAll(/\s+/g, '-').toLowerCase()}-report.${ext}`;
    downloadText(filename, html, 'text/html;charset=utf-8');
    recordChange({
      action: 'Generated finding report',
      targetType: 'report',
      targetId: issue.id,
      targetName: issue.title,
      projectId: project.id,
      details: `Format: ${format}`,
    });
    return { path: filename };
  }

  if (format === 'pdf') {
    printHtml(html);
    recordChange({
      action: 'Generated finding report',
      targetType: 'report',
      targetId: issue.id,
      targetName: issue.title,
      projectId: project.id,
      details: 'Format: pdf',
    });
    return { path: 'browser-print-dialog' };
  }

  return { error: 'Unsupported format.' };
};

export const getReportPreview = async (
  projectId: string
): Promise<{ html?: string; error?: string }> => {
  const projects = await fetchProjects();
  const project = projects.find((entry) => entry.id === projectId);
  if (!project) return { error: 'Project not found.' };
  const issues = await fetchIssues(projectId);

  recordChange({
    action: 'Viewed project report preview',
    targetType: 'report',
    targetId: project.id,
    targetName: project.name,
    projectId: project.id,
    details: 'Action: preview',
  });

  return {
    html: makeProjectHtml(project, issues),
  };
};
